#!/bin/bash

words=$(echo $1 | tr ' ' '\n')
times=$(echo $1 | wc -w)

for i in $(eval echo {1..$(($times-1))}) ; do
    first=$(echo $words | tr ' ' '\n' | head -$i | tr '\n' ' ' | rev | cut -c2- | rev )
    second=$(echo $words | tr ' ' '\n' | tail -$(($times-$i)) | tr '\n' ' ' | rev | cut -c2- | rev)
    echo -n '('$first,$second')'
done


